version: '3.5'

services:
  dotnet-api:
    container_name: ResearchesUFU_API
    image: dotnet
    depends_on:
      - "postgres_database"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - researches-ufu-network
      
  postgres_database:
      container_name: ResearchesUFU_DB
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres:/data/postgres
      restart: always
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "ResearchesUFU"
      networks:
        - researches-ufu-network
    
networks:
  researches-ufu-network:
    driver: bridge
    
volumes:
  postgres: