// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResearchesUFU.API.Context;

#nullable disable

namespace ResearchesUFU.API.Migrations
{
    [DbContext(typeof(ResearchesUFUContext))]
    [Migration("20230130203228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchesUFU.API.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverPhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Birthdate = "20/07/1990",
                            CoverPhotoUrl = "",
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Elisabete Sintra Barateiro",
                            PhoneNumber = "553498153388",
                            ProfilePictureUrl = "",
                            UserId = 1,
                            UserType = "Publicator"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Birthdate = "05/05/1999",
                            CoverPhotoUrl = "",
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Dominic Frota Godoi",
                            PhoneNumber = "553498851389",
                            ProfilePictureUrl = "",
                            UserId = 2,
                            UserType = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Birthdate = "21/07/1993",
                            CoverPhotoUrl = "",
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Ricardo Guedes Neres",
                            PhoneNumber = "553498153388",
                            ProfilePictureUrl = "",
                            UserId = 3,
                            UserType = "Publicator"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Birthdate = "04/12/2001",
                            CoverPhotoUrl = "",
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Cristiano Araújo Távora",
                            PhoneNumber = "553498851389",
                            ProfilePictureUrl = "",
                            UserId = 4,
                            UserType = "Editor"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Birthdate = "01/06/2000",
                            CoverPhotoUrl = "",
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Eric Cadaval Ornelas",
                            PhoneNumber = "553498851389",
                            ProfilePictureUrl = "",
                            UserId = 5,
                            UserType = "Editor"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "SI",
                            Name = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "CC",
                            Name = "Ciência da Computação"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "BIO",
                            Name = "Biologia"
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "S",
                            Name = "Sociologia"
                        },
                        new
                        {
                            Id = 5,
                            Acronym = "Art",
                            Name = "Artes"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearchStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Researches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "02/02/2022",
                            ResearchStructure = "",
                            Status = "Em andamento",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image01.png",
                            Title = "Inteligência artificial para análise de investimentos."
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "19/09/2019",
                            ResearchStructure = "",
                            Status = "Finalizada",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image02.jpg",
                            Title = "Estudo de técnicas de Cloud Computing"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "01/01/2011",
                            ResearchStructure = "",
                            Status = "Cancelada",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image03.jpg",
                            Title = "Os beneficios do café"
                        },
                        new
                        {
                            Id = 4,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "012/08/2018",
                            ResearchStructure = "",
                            Status = "Finalizada",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image04.jpg",
                            Title = "UFU..."
                        },
                        new
                        {
                            Id = 5,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "20/03/2021",
                            ResearchStructure = "",
                            Status = "Em andamento",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image05.png",
                            Title = "DNA..."
                        },
                        new
                        {
                            Id = 6,
                            LastUpdated = "30/01/2023 20:32:27",
                            PublicationDate = "09/12/2016",
                            ResearchStructure = "",
                            Status = "Em andamento",
                            Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultricies dictum varius. Donec ultrices nibh eget tellus aliquet tincidunt. Proin fringilla leo quis nibh sollicitudin hendrerit. Nullam et massa non felis vestibulum ornare at eget velit. Maecenas tincidunt commodo tellus, quis vehicula massa pharetra a. Suspendisse eu fermentum nulla. Nam tempor velit vitae commodo interdum. Mauris feugiat euismod semper. Nam porta vitae eros eget lobortis. Pellentesque sed neque sit amet sapien vestibulum consectetur. In at neque in lectus pulvinar ultrices. Mauris condimentum gravida metus nec pretium. Quisque a venenatis neque. Aenean quis tellus elementum, laoreet tortor in, vehicula lacus. Integer tellus massa, lacinia sit amet molestie vel, convallis a ante.\nNulla euismod justo ut rhoncus mattis. Sed quam quam, scelerisque sagittis nibh in, rutrum lacinia odio. Suspendisse gravida leo in elit elementum, at placerat arcu consequat. Integer justo dui, gravida sit amet ipsum non, vehicula fringilla nisl. Integer pretium vulputate purus, non efficitur tortor vestibulum nec. Etiam posuere nunc ipsum, vel venenatis ipsum vehicula eget. Mauris vulputate nibh at blandit euismod. Nulla laoreet feugiat efficitur. Suspendisse sit amet vulputate turpis, vitae tristique metus. Integer et condimentum arcu. Nulla efficitur dolor tortor, vitae sodales lectus rhoncus id. Etiam mollis porta urna sed tempus.",
                            Thumbnail = "https://raw.githubusercontent.com/MateusFerreiraSilva/ResearchesUFU/master/back-end/ResearchesUFU.API/Images/image06.jpg",
                            Title = "Artes..."
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchAuthor", b =>
                {
                    b.Property<int>("ResearchId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.HasKey("ResearchId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("ResearchAuthor");

                    b.HasData(
                        new
                        {
                            ResearchId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            ResearchId = 1,
                            AuthorId = 2
                        },
                        new
                        {
                            ResearchId = 2,
                            AuthorId = 1
                        },
                        new
                        {
                            ResearchId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            ResearchId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            ResearchId = 5,
                            AuthorId = 3
                        },
                        new
                        {
                            ResearchId = 6,
                            AuthorId = 5
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchField", b =>
                {
                    b.Property<int>("ResearchId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.HasKey("ResearchId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("ResearchField");

                    b.HasData(
                        new
                        {
                            ResearchId = 1,
                            FieldId = 1
                        },
                        new
                        {
                            ResearchId = 1,
                            FieldId = 2
                        },
                        new
                        {
                            ResearchId = 2,
                            FieldId = 1
                        },
                        new
                        {
                            ResearchId = 2,
                            FieldId = 2
                        },
                        new
                        {
                            ResearchId = 3,
                            FieldId = 3
                        },
                        new
                        {
                            ResearchId = 4,
                            FieldId = 4
                        },
                        new
                        {
                            ResearchId = 5,
                            FieldId = 3
                        },
                        new
                        {
                            ResearchId = 6,
                            FieldId = 5
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchTag", b =>
                {
                    b.Property<int>("ResearchId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ResearchId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ResearchTag");

                    b.HasData(
                        new
                        {
                            ResearchId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ResearchId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ResearchId = 1,
                            TagId = 4
                        },
                        new
                        {
                            ResearchId = 2,
                            TagId = 3
                        },
                        new
                        {
                            ResearchId = 3,
                            TagId = 5
                        },
                        new
                        {
                            ResearchId = 3,
                            TagId = 6
                        },
                        new
                        {
                            ResearchId = 4,
                            TagId = 12
                        },
                        new
                        {
                            ResearchId = 4,
                            TagId = 13
                        },
                        new
                        {
                            ResearchId = 5,
                            TagId = 5
                        },
                        new
                        {
                            ResearchId = 5,
                            TagId = 9
                        },
                        new
                        {
                            ResearchId = 6,
                            TagId = 10
                        },
                        new
                        {
                            ResearchId = 6,
                            TagId = 11
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "artificial intelligence"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "ai"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "cloud computing"
                        },
                        new
                        {
                            Id = 4,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "computer science"
                        },
                        new
                        {
                            Id = 5,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "biochemistry"
                        },
                        new
                        {
                            Id = 6,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "coffe"
                        },
                        new
                        {
                            Id = 8,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "ufu"
                        },
                        new
                        {
                            Id = 9,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "dna"
                        },
                        new
                        {
                            Id = 10,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "artes"
                        },
                        new
                        {
                            Id = 11,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Pintura a Óleo"
                        },
                        new
                        {
                            Id = 12,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Estudos sociais"
                        },
                        new
                        {
                            Id = 13,
                            LastUpdated = "30/01/2023 20:32:27",
                            Name = "Sociologia"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Email = "teste@ufu.br",
                            LastUpdated = "30/01/2023 20:32:27",
                            PasswordHash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Email = "batata@ufu.br",
                            LastUpdated = "30/01/2023 20:32:27",
                            PasswordHash = "f4610aa514477222afac2b77f971d069780ca2846f375849f3dfa3c0047ebbd1"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Email = "teste2@ufu.br",
                            LastUpdated = "30/01/2023 20:32:27",
                            PasswordHash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Email = "batata2@ufu.br",
                            LastUpdated = "30/01/2023 20:32:27",
                            PasswordHash = "f4610aa514477222afac2b77f971d069780ca2846f375849f3dfa3c0047ebbd1"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Email = "teste3@ufu.br",
                            LastUpdated = "30/01/2023 20:32:27",
                            PasswordHash = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Author", b =>
                {
                    b.HasOne("ResearchesUFU.API.Models.User", "User")
                        .WithOne("Author")
                        .HasForeignKey("ResearchesUFU.API.Models.Author", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchAuthor", b =>
                {
                    b.HasOne("ResearchesUFU.API.Models.Author", "Author")
                        .WithMany("ResearchAuthor")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchesUFU.API.Models.Research", "Research")
                        .WithMany("ResearchAuthor")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchField", b =>
                {
                    b.HasOne("ResearchesUFU.API.Models.Field", "Field")
                        .WithMany("ResearchField")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchesUFU.API.Models.Research", "Research")
                        .WithMany("ResearchField")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchTag", b =>
                {
                    b.HasOne("ResearchesUFU.API.Models.Research", "Research")
                        .WithMany("ResearchTag")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchesUFU.API.Models.Tag", "Tag")
                        .WithMany("ResearchTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Research");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Author", b =>
                {
                    b.Navigation("ResearchAuthor");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Field", b =>
                {
                    b.Navigation("ResearchField");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Research", b =>
                {
                    b.Navigation("ResearchAuthor");

                    b.Navigation("ResearchField");

                    b.Navigation("ResearchTag");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Tag", b =>
                {
                    b.Navigation("ResearchTag");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.User", b =>
                {
                    b.Navigation("Author")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
