// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResearchesUFU.API.Context;

#nullable disable

namespace ResearchesUFU.API.Migrations
{
    [DbContext(typeof(ResearchesUFUContext))]
    partial class ResearchesUFUContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchesUFU.API.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "SI",
                            Name = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "CC",
                            Name = "Ciência da Computação"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "BIO",
                            Name = "Biologia"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Researches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = "28/01/2023 20:10:53",
                            PublicationDate = "02/02/2022",
                            Status = "Em andamento",
                            Summary = "AAAAA",
                            Thumbnail = "https://cdn.vox-cdn.com/thumbor/WR9hE8wvdM4hfHysXitls9_bCZI=/0x0:1192x795/1400x1400/filters:focal(596x398:597x399)/cdn.vox-cdn.com/uploads/chorus_asset/file/22312759/rickroll_4k.jpg",
                            Title = "Primeira Pesquisa"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = "28/01/2023 20:10:53",
                            PublicationDate = "19/09/2019",
                            Status = "Finalizada",
                            Summary = "BBBB",
                            Thumbnail = "https://cdn.vox-cdn.com/thumbor/WR9hE8wvdM4hfHysXitls9_bCZI=/0x0:1192x795/1400x1400/filters:focal(596x398:597x399)/cdn.vox-cdn.com/uploads/chorus_asset/file/22312759/rickroll_4k.jpg",
                            Title = "Segunda Pesquisa"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = "28/01/2023 20:10:53",
                            PublicationDate = "01/01/2011",
                            Status = "Cancelada",
                            Summary = "Potato",
                            Thumbnail = "https://static.mundoeducacao.uol.com.br/mundoeducacao/conteudo_legenda/01325ea5fd7fd4ecab7e209393bf6188.jpg",
                            Title = "Batata"
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchField", b =>
                {
                    b.Property<int>("ResearchId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.HasKey("ResearchId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("ResearchField");

                    b.HasData(
                        new
                        {
                            ResearchId = 1,
                            FieldId = 1
                        },
                        new
                        {
                            ResearchId = 2,
                            FieldId = 1
                        },
                        new
                        {
                            ResearchId = 2,
                            FieldId = 2
                        },
                        new
                        {
                            ResearchId = 3,
                            FieldId = 3
                        });
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.ResearchField", b =>
                {
                    b.HasOne("ResearchesUFU.API.Models.Field", "Field")
                        .WithMany("ResearchField")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchesUFU.API.Models.Research", "Research")
                        .WithMany("ResearchField")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Field", b =>
                {
                    b.Navigation("ResearchField");
                });

            modelBuilder.Entity("ResearchesUFU.API.Models.Research", b =>
                {
                    b.Navigation("ResearchField");
                });
#pragma warning restore 612, 618
        }
    }
}
